MODEL   = google:gemini-pro --no-think
LANG    = Italian
LCODE   = gemini1-it
FIXES   = --fix $(SRCDIR)/2-fix.xml
LANGS   = -t "English,Latin,Interlingua,French,Spanish,Portuguese,Romanian,Esperanto"

include ../common.mk
